### ISSUE TITLE
data-start attribute not longer being applied to the <pre> element

### ISSUE THREAD

**Issue by Syn-Tylor** [shipshapecode/ember-prism#241]
Looking at the prism documentation [here](https://prismjs.com/plugins/line-numbers/) it states "_Optional: You can specify the data-start (Number) attribute on the pre element. It will shift the line counter._" Adding something like `data-start={{@start}}` to the pre element in the code-block.hbs template corrects it.

**Comment by rwwagner90** [comment]
@Syn-Tylor are you saying you were able to add this before or this is a new feature request?

**Comment by Syn-Tylor** [comment]
Hey, ya it was working previously (on v0.5.0 at least).

I believe (could be wrong on this) it is not working because the previous implementation used a `pre` tagName. The newer version (v0.9.1) still does this, but in its template the `...attributes` (_where the data-start is contained_) is being added to the `<code>` element instead of the `<pre>` element.

**Comment by rwwagner90** [comment]
@Syn-Tylor that seems logical. Perhaps we should move `...attributes`?

**Comment by Syn-Tylor** [comment]
Uhm.. not too sure. 
I will play with it a bit and see what the effects are. Set myself a reminder monday night to test it out a bit.

**Comment by rwwagner90** [comment]
Sounds good, keep me posted!

**Comment by Syn-Tylor** [comment]
So played around w it a bit today. Basically 2 routes I played with

a) adding `data-start={{@start}}` to `<pre>` element
   - this worked w/o any notable issue
b) moved `...attributes` from `<CodeInline>` to `<pre>`
   - this had some unintended consequences regarding styles

**Comment by rwwagner90** [comment]
@Syn-Tylor the first option sounds good for now. Would you like to open a PR?

**Comment by Syn-Tylor** [comment]
Hey, sry its been a while. Looked back at this today and created a branch with the fix, documentation update, and test coverage. Unfortunately (and I can't figure away around this) Prism uses CSS `counter-increment` property to show the actual line number. Meaning you cannot assert on the contents of the element as it is not bound in the DOM (ref: https://stackoverflow.com/questions/532073/how-can-i-read-the-applied-css-counter-value) . I could just leave that test out though. 

_Note: sorta blocked on this though as I can't push the branch up, getting permission error on `git push -u origin fix-241-data-start-attribute-not-working`_. Tried a few things like removing/regenerating SSH keys and publishing the branch via GitHub desktop, but got the same error.

**Comment by Syn-Tylor** [comment]
opened PR https://github.com/shipshapecode/ember-prism/pull/342
