### ISSUE TITLE
Value not updating dynamically

### ISSUE THREAD

**Issue by pRatikSathaye** [shipshapecode/ember-prism#27]
I am using ember-prism in my ember application.
`{{#code-block language="json"}}
{{jsonData}}
{{/code-block}}`
When value of `jsonData` changes it does not render in {{code-block}}, but I can see it changed when I print jsonData on the page without {{code-block}} by just using {{jsonData}}.

**Comment by rwwagner90** [comment]
Hi @pRatikSathaye, this is correct. It does not update dynamically. It sets the innerHTML one time in `didRender`. https://github.com/shipshapecode/ember-prism/blob/master/addon/components/code-block.js#L12

Would you be interested in submitting a PR with a fix?

**Comment by apellerano-pw** [comment]
I also wanted this functionality but the component interface ended up being drastically different so I didn't want to blend it with this lib. For reference, here's my implementation:

component.js
```javascript
/* global Prism */
import Component from '@ember/component';
import { computed } from '@ember/object';

export default Component.extend({
  classNameBindings: ['languageClass'],
  tagName: 'pre',

  code: '',
  language: 'markup',

  languageClass: computed('language', function () {
    return `language-${this.get('language')}`;
  }),

  prismCode: computed('code', function () {
    const code = this.get('code');
    if (!code) return '';

    const grammar = Prism.languages[this.get('language')];
    if (!grammar) return '';

    return Prism.highlight(code, grammar);
  }),
});
```

template.hbs
```handlebars
<code class={{languageClass}}>{{{prismCode}}}</code>
```

usage:
```handlebars
{{syntax-highlight language="markup" code=myHtmlVar}}
```

**Comment by rwwagner90** [comment]
@apellerano-pw we can incorporate some of these changes probably. No reason we shouldn't support this here, right?

**Comment by simonihmig** [comment]
@apellerano-pw I would be interested in this as well. I agree it should be not too hard to add support for the source passed as a property rather than a block template. Using something like `{{#if hasBlock}}` it should be possible to support both APIs (although the block from would not support dynamic updates).

Would you or someone else be willing to work on it? Otherwise I fear I would have to do it... 😬

**Comment by rwwagner90** [comment]
@simonihmig I may be able to work on something, but I would not mind if you guys wanted to go ahead and throw something together 😃
