### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buildPlaceholders' of undefined

### ISSUE THREAD

**Issue by nightire** [shipshapecode/ember-prism#29]
![image](https://user-images.githubusercontent.com/1104018/40702608-14fde7de-6415-11e8-9457-58fbf6da7049.png)

**Comment by nightire** [comment]
I should have mentioned it happened on an ember v3 app, if it helps.

**Comment by nightire** [comment]
Okay, I've figured it out, in case of anyone encounters similar issue, you need to set prism's component dependencies explicitly, see this issue: https://github.com/PrismJS/prism/issues/1394

In my case, I made this change in `ember-cli-build.js` file:

![image](https://user-images.githubusercontent.com/1104018/40708578-5eb0ba80-6426-11e8-8479-b745215b2b55.png)

**Comment by oliverlangan** [comment]
This was super useful, by the way. Thanks. Not sure how we're supposed to know that `markup-templating` is effectively a requirement for `handlebars`.

**Comment by rwwagner90** [comment]
@nightire @oliverlangan it is a requirement for hbs? We could perhaps build some of this in.

**Comment by oliverlangan** [comment]
Yes, that is what I saw. I had originally set my `components` array like so:
```
   'components': ['css', 'handlebars', 'javascript', 'markup', 'scss'],
```
and was seeing the same error as above. Once I added `'markup-templating'` it began to work as expected.

**Comment by rwwagner90** [comment]
@oliverlangan where is `markup-templating` used?

**Comment by oliverlangan** [comment]
I added it to the `components` array:
```
   'components': ['css', 'handlebars', 'javascript', 'markup', 'markup-templating', 'scss'],
```

I am not specifically using it, but it appears to be a dependency of `handlebars`.

**Comment by rwwagner90** [comment]
@oliverlangan ah, yes, it does appear you are correct. Perhaps we should document this in the README? Would you like to open a PR?
