### ISSUE TITLE
Is calling `setup()` necessary?

### ISSUE THREAD

**Issue by MariannaAtPlay** [shipshapecode/ember-prism#315]
Hello!

Thank you for maintaining this lib!

There seems to be a discrepancy between the README here vs the docs on [NPM](https://www.npmjs.com/package/ember-prism)

Here the docs say that this step is necessary:
```
import { setup } from 'ember-prism';
...
setup();
```
while on NPM this step is not mentioned. 

When I attempted to follow this guideline I was getting an error about the module not being found. But the functionality seems to be working even w/o calling `setup()`.

Please clarify and update README if this step is not needed.

**Comment by rwwagner90** [comment]
Hi @MariannaAtPlay we probably have not released since those changes were added.

**Comment by rwwagner90** [comment]
I just released 0.10.0, please give it a try!

**Comment by MariannaAtPlay** [comment]
Thanks Robert!
I am using `0.9.1` and it seems to be working w/o needing to call `setup()`. 
Mostly wanted to confirm and ask you to update README to save confusion for other people.

**Comment by rwwagner90** [comment]
It is a necessary step, we just hadn't released a new version since the docs were updated. The docs on npm should now be up to date.
