### ISSUE TITLE
Unexpectedly found "! ~" when slicing source, but expected " "

### ISSUE THREAD

**Issue by charlesfries** [shipshapecode/ember-prism#447]
Seeing the following build time warning in 0.12.0:

```
[Babel: ember-prism > applyPatches]unexpectedly found "! ~" when slicing source, but expected " "
unexpectedly found "! ~" when slicing source, but expected " "
unexpectedly found "! ~" when slicing source, but expected " "
unexpectedly found "! ~" when slicing source, but expected " "
```

```json
"ember-cli": "~4.1.0",
"ember-prism": "^0.12.0",
"ember-source": "~3.28.8",
```

Seems to be caused by these template comments: https://github.com/shipshapecode/ember-prism/blob/c9b1ba0693b830390f274dbd3216e158508891a7/addon/components/code-block.hbs#L4

**Comment by rwwagner90** [comment]
@charlesfries thanks for reporting! We were using that to remove whitespace before. I wonder why it all the sudden stopped working?

**Comment by charlesfries** [comment]
Seems to be related to `ember-cli-htmlbars@6.0.1` https://github.com/emberjs/ember.js/issues/19392

Downgrading `ember-cli-htmlbars` to 6.0.0 seems to fix the issue on my fork.
