### ISSUE TITLE
Splattributes seem to be applied twice

### ISSUE THREAD

**Issue by ijlee2** [shipshapecode/ember-prism#84]
Hello 👋. I was working on [updating dependencies for Octane cheatsheet](https://github.com/ember-learn/ember-octane-vs-classic-cheat-sheet/pull/41). I think the rendering tests began to fail when I updated `ember-prism` to the current release `v0.7.0`.

In development and test environments, I noticed that the test selector `data-test-code-snippet` appeared twice. One on the `<pre>` tag and another on the `<code>` tag inside. (The CSS class `.language-bash` occurred twice before the addon upgrade, so I think we can ignore this one.)

<img width="540" alt="test selectors" src="https://user-images.githubusercontent.com/16869656/85209152-2c6b8200-b2fb-11ea-8486-8e5ff5f4b457.png">

I wondered if this happened because the `<CodeBlock>` component extends a classic component, while `...attributes` is relatively new.

Here's how `ember-prism` is used in the app:

```handlebars
{{!-- app/components/code-snippet/template.hbs --}}

{{#let (get-code-snippet @fileName) as |snippet|}}
  <CodeBlock
    data-test-code-snippet
    @code={{snippet.source}}
    @language={{get-prism-language snippet.language}}
  />
{{/let}}
```

**Comment by rwwagner90** [comment]
@ijlee2 that sounds correct. We probably should update this addon to use more modern syntax.

**Comment by ijlee2** [comment]
I made a draft PR in https://github.com/shipshapecode/ember-prism/pull/85 so that you can continue the work if you'd like. I can help some more.

Currently, the backing classes of `<NewCodeBlock>` and `<NewCodeInline>` are the same; only the templates differ slightly. We _could_ try to make 1 base class and have both classes extend it, but I think it'll be easier to maintain and add features later if we don't do inheritance.

To do:

- Update application and rendering tests
- Decide where to place splattributes in each component
- Update documentation

**Comment by rwwagner90** [comment]
@ijlee2 thanks for doing that spike! I'll take a look sometime this week.
